global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "storage_api"
    scrape_interval: 5s
    metrics_path: /api/metrics
    static_configs:
      - targets: ["storage_api:5000"]
