service:
  enabled: true
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30100

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server:9090
      password:
      user:
      database:
      basicAuth: true
      basicAuthUser: admin
      basicAuthPassword: foobar
      withCredentials:
      isDefault: true
      jsonData:
        graphiteVersion: "1.1"
        tlsAuth: false
        tlsAuthWithCACert: false
      secureJsonData:
        tlsCACert:
        tlsClientCert:
        tlsClientKey:
      version: 1
      editable: true
